apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cloudfusion-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: cloudfusion-tap
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  serviceClaims:
    - name: db
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: customer-profile-database
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: team-tanzu
        system: cloudfusion
        description: CloudFusion REST API built using Spring Boot powered by Tanzu Application Platform Accelerators
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
